version: 2
updates:
  # Update Rust crate dependencies in the root crate
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  # Update Rust crate dependencies in the proto crate
  - package-ecosystem: "cargo"
    directory: "/proto"
    schedule:
      interval: "weekly"
